### ISSUE TITLE
[BUG] fcw-link.lilico.app prompts the app to be opened in Flow Ref, not the latest Flow Wallet app.

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#1]
### Current Behavior

fcw-link.lilico.app prompts the app to be opened in Flow Ref, not the latest Flow Wallet app.

### Expected Behavior

fcw-link.lilico.app prompts Flow Wallet to be opened, not Flow Ref.

### Steps To Reproduce

1. Navigate to Flow Port on Mobile
2. Select Flow Wallet Mobile
3. Select "Open in Flow Ref" on fcw-link.lilico.app

### Environment

```markdown
- iOS
```

**Comment by Peppermint1020** [comment]
Hao already solved this issue.
Now fcw-link.lilico.app prompts the app to be opened in Flow wallet.
