### ISSUE TITLE
[Feature] Homepage Wallet Connect Chip

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#11]
# Feature

Users sometimes have difficulty understanding what icon corresponds to the button to open the Wallet Connect camera. We should animate-in a chip when the homepage is opened, which displays the text "Connect to App" beside the Wallet Connect icon, that later collapses into just the icon. This way, it's more obvious to the user and educates the user how to open the Wallet Connect camera.

<img width="790" alt="Group 47437" src="https://github.com/Outblock/FRW/assets/14852344/15b3969b-5db6-4a18-beee-6b43cba66cd8">

**Comment by lmcmz** [comment]
@KK-UIUX review this
