### ISSUE TITLE
[Feature] Misc Copy Updates

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#12]
# Feature

Copy update issues:

https://github.com/Outblock/FRW-iOS/issues/161
https://github.com/Outblock/FRW-iOS/issues/138
https://github.com/Outblock/FRW-iOS/issues/161
https://github.com/Outblock/FRW-iOS/issues/162

**Comment by Peppermint1020** [comment]
https://github.com/Outblock/FRW-iOS/issues/169
https://github.com/Outblock/FRW-iOS/issues/168
https://github.com/Outblock/FRW-iOS/issues/167
https://github.com/Outblock/FRW-iOS/issues/166

**Comment by lmcmz** [comment]
@jaymengxy  Android need follow up

**Comment by lmcmz** [comment]
- [x] Android
- [x] iOS
