### ISSUE TITLE
[BUG] Incorrectly asking for password when restoring account using recovery phrase (old) workflow

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#14]
### Current Behavior

When recovering an account using the "recovery phrase (old)" workflow, Flow Wallet asks the user to input a password. This is unnecessary, as only the recovery phrase is required to restore the account without requiring a password.

### Expected Behavior

When recovering an account using the "recovery phrase (old)" workflow, Flow Wallet only asks the user to input their recovery phrase, not a password.

### Steps To Reproduce

1. Recover an account using the "Recovery Phrase (Old)" workflow
2. Input a recovery-phrase
3. Observe the wallet ask for a password.

### Environment

```markdown
- iOS
- Extension
```

**Comment by lmcmz** [comment]
@JeffreyDoyle  Could you double check which platform it is ?

**Comment by lmcmz** [comment]
Issue happens in Extension

**Comment by lmcmz** [comment]
@lmcmz  ask Ali for more detail
