### ISSUE TITLE
[Feature] Account creation Secure Enclave slides

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#15]
# Feature

When the user creates a new account using Flow Wallet, there is some time while the account creation transaction progresses that the application waits in a loading state. We need to use this time to show the user why Flow Wallet is special, and how the fact that it uses Secure Enclave to secure their accounts is important.

While the account creation transaction is happening, we should display slides with information the user can read through:

![Group 47438](https://github.com/Outblock/FRW/assets/14852344/ba481309-61b0-47f2-acae-d47ce71af4ad)

@lmcmz @KK-UIUX -- Could you please help flush out these designs? These slides should be displayed after the user creates a new account, and while the account creation process / transaction occurs. The slides are available in the "Product Sketches" of the figma file

**Comment by Peppermint1020** [comment]
- [x] ios
- [x] Android
