### ISSUE TITLE
[BUG] NFTs displayed for wrong account on NFT page

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#16]
### Current Behavior  

When viewing an account's NFTs, sometimes NFTs owned by another account in the wallet are displayed.

![IMG_8593](https://github.com/Outblock/FRW/assets/14852344/7c6f65d7-c685-48df-b399-67f27032af7c)

### Expected Behavior  

Only NFTs for the active account are displayed in the NFT view.

### Steps To Reproduce  

1. Open an account that owns NFTs in the wallet
2. Change profile to an account that doesn't own any NFTs
3. Observe the previous accounts NFTs displayed.

 ### Environment  
 
 ```markdown
  - iOS 
  ```

**Comment by lmcmz** [comment]
- [x] iOS
- [x] Android
- [x] Extension

**Comment by Peppermint1020** [comment]
IOS version 2.1.3(6) still display for wrong account on NFT grid page.


https://github.com/Outblock/FRW/assets/87978227/5cb4654c-97e7-44b4-a2a4-0172cec9ff98

And extension version 2.1.8 still have this issue.


https://github.com/Outblock/FRW/assets/87978227/3fd302fd-9cf1-4e95-91fa-a1a509633836

**Comment by lmcmz** [comment]
- [ ] iOS
- [ ] Extension

**Comment by lmcmz** [comment]
@Peppermint1020  revisit this

**Comment by Peppermint1020** [comment]
- [ ]  iOS
In ios prod version 2.1.5(1), there still some issues for NFTs displayed for wrong account on NFT page.
(1) NFTs displayed for wrong account on NFT page when switch network.
(2) NFTs displayed for wrong account on NFT page when switch profile.





https://github.com/Outblock/FRW/assets/87978227/57e9a5a9-16e7-48d4-ab56-c425f9f9af21




- [ v]  Extension


https://github.com/Outblock/FRW/assets/87978227/622c3041-429d-489f-81ee-2e841c1beb0b


- [ v] android


https://github.com/Outblock/FRW/assets/87978227/0b798bbc-6fed-45de-a1fe-c4d124d8b72f

**Comment by Peppermint1020** [comment]
Still show previous account NFT when switch networks.


https://github.com/Outblock/FRW/assets/87978227/65032ec3-af0e-4c8c-aa7c-c2bbcb877ffb
