### ISSUE TITLE
[BUG] Incorrect assets displayed for current account in Flow Wallet Extension, unable to switch accounts

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#17]
### Current Behavior

A user has accounts A and B on Flow Wallet extension. They authenticate with an application using account A. In their wallet, assets from account B are displayed, when the active account is account A. When the user attempts to account switch to account B in the wallet UI, they're prompted to resubmit their password but the password fails to validate.

### Expected Behavior

When an account is active in the wallet only it's assets are displayed. Users can switch to other accounts within the wallet and their correct password works.

### Steps To Reproduce

1. Create FW Extension accounts A and B
2. Aquire some assets to account A and B
3. Login to application with account A
4. Observe assets in account B displayed
5. Attempt to switch to account B
6. Observe correct password is not accepted for account B

### Environment

```markdown
- Extension
```

### Notes

- A video example of this is available internally. As it contains user data, we cannot attach it to this issue. Please reach out to @JeffreyDoyle to see the video.

**Comment by lmcmz** [comment]
Issue fixed on child account while switching between account.
Please try with new version `2.1.8`
