### ISSUE TITLE
[BUG] link.lilico.app Incorrectly branded and deeplinked as/to Lilico instead of Flow Wallet

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#19]
### Current Behavior

link.lilico.app & link.lilico.app/wc are currently branded using the old Lilico branding, and deeplinks to Lilico instead of Flow Wallet. It must be correctly rebranded and deeplinked to Flow Wallet.

### Expected Behavior

link.lilico.app is correctly branded to Flow Wallet

### Steps To Reproduce

1. Open link.lilico.app or link.lilico.app/wc
2. Observe old Lilico branding

### Environment

```markdown
- Extension
- iOS/Android
```

### Notes
![IMG_0760](https://github.com/Outblock/FRW/assets/14852344/78c396b8-7cf9-4586-ab84-80267a369f4c)
![IMG_0759](https://github.com/Outblock/FRW/assets/14852344/94be96b5-d8e2-42db-851a-9815ffbd95b2)

**Comment by lmcmz** [comment]
Current link is https://frw-link.lilico.app/, need migrate under flow.com domain
