### ISSUE TITLE
[BUG] Flow Wallet Extension cannot transfer tokens created by Toucans (eg: Beaver Token)

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#2]
### Current Behavior

Flow Wallet Extension errors when transferring tokens created by Toucans (eg: Beaver Token)
![Screenshot 2024-04-18 at 1 55 37 PM](https://github.com/Outblock/FRW/assets/14852344/14f3d377-6dee-45cf-8cf3-2b3f72826a1a)

### Expected Behavior

Flow Wallet Extension can transfer tokens created by Toucans.

### Steps To Reproduce

1. Aquire some Beaver token
2. Attempt to transfer Beaver token using Flow Wallet Extension

### Environment

```markdown
- Chrome Extension
```

**Comment by Peppermint1020** [comment]
In the web extension version 2.1.7 (debug), when transferring Beaver Token, the send page does not show that the transaction failed now.

![Image](https://github.com/Outblock/FRW/assets/87978227/381de5b9-8be3-4c38-8cd9-97cbadde658b)
The remaining issue we have is that Beaver Token is not in our token list. If we do not enable this token in the receiver's account, the transaction will fail.
The error message can be found here: [link](https://www.flowdiver.io/tx/8735be96fdb5a059a6708c6e65e6a3a7c58f57a396419681a8ee8d9772bd600e).

Han is working on this issue."

**Comment by Peppermint1020** [comment]
This issue has already been resolved. Han has updated the token list, allowing users to enable the Beaver token and transfer it successfully.

We will be publishing a debug build this week, which will include this correction. Additionally, the mobile app will update its token list once they have finished addressing other issues in the FRW repository.
