### ISSUE TITLE
[BUG] Flow Wallet Extension fails to import account from 12-word seed phrase

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#20]
### Current Behavior

A user with a 12-word recovery phrase can successfully recover their account by using it with Flow Wallet Mobile, but on Flow Wallet Extension the account cannot be found.

### Expected Behavior

A 12-word recovery phrase can be successfully used to recover accounts across all platforms, Mobile iOS/Android and Extension.

### Steps To Reproduce

1. Recover an account from a 12-word seed phrase on Mobile
2. Observe the account recovered successfully
3. Recovery the account using the same 12-word seed phrase on Extension
4. Observe no account found

### Environment

```markdown
- Extension
```

### Notes
![image (12)](https://github.com/Outblock/FRW/assets/14852344/f239ff09-c557-4c31-b355-1fecdcdbaba0)

**Comment by lmcmz** [comment]
Which wallet create the 12 seed phrase ? Is other wallet ? And is it mobile or extension ?

**Comment by JeffreyDoyle** [comment]
@lmcmz The seed phrase was created on Flow Wallet Extension

**Comment by JeffreyDoyle** [comment]
Resolved in Extension version `2.1.9`
