### ISSUE TITLE
[Feature] Ensure Flow Wallet colour branding used across all copy

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#21]
## Feature

On some copy the old orange lilico branding is still used.

We must ensure all copy/branding is updated to Flow Wallet, including any copy colours.

## Notes 
![image (12)](https://github.com/Outblock/FRW/assets/14852344/b8b613a2-e197-4182-8e56-2000255d67ec)

**Comment by KK-UIUX** [comment]
It is not the old brand color. At this part, the orange color is used as an alert color.
