### ISSUE TITLE
[BUG] Wallet Connect listing displays as Lilico

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#22]
### Current Behavior

On the WalletConnect explore listing for Flow Wallet, the listing has Lilico in the URL and core.flow.com as the webpage address.

### Expected Behavior

If possible, the URL should make reference to Flow Wallet and the website updated to wallet.flow.com

### Steps To Reproduce

1. Navigate to Flow Wallet's listing on WalletConnect explorer
2. Observe Lilico in the address bar and core.flow.com as the website.

### Environment

```markdown
```

### Notes
<img width="817" alt="Screen Shot 2024-05-15 at 5 24 06 PM" src="https://github.com/Outblock/FRW/assets/14852344/ef65e8a2-0620-4f30-bb37-d23bbb5dda7e">

**Comment by Peppermint1020** [comment]
Already updated the the website to wallet.flow.com
