### ISSUE TITLE
[BUG] Selecting "View More" button doesn't open account list to its expended form.

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#23]
### Current Behavior

Selecting "View More" button doesn't open the account list to its expended form.

### Expected Behavior

Selecting "View More" button opens the account list to its expended form.

### Steps To Reproduce

1. Navigate to the account selector in the iOS app.
2. Press the "View More" button on the accounts list.
3. Observe the accounts list not open to it's expended form

### Environment

```markdown
- iOS
```

### Related Issues

- https://github.com/Outblock/FRW-iOS/issues/178

### Notes
<img width="817" alt="Screen Shot 2024-05-15 at 5 24 06 PM" src="https://d38gnqwzxziyyy.cloudfront.net/attachments/bugs/22001891/0a377bf06e076a8508f410169626fa6f_original/34068627/2024051612164325743785.jpg?Expires=4871546257&Signature=FuCNoP7zI7fUyK8~G6Ea9A-q6C9O5OKcuJd0rfTeFzdGSpR~gAhMFoK4p0Vydl6d7o5D1Qog4qWGZ11vjSezacVPHLc30l0hMSR5jfw4iD2wqwPUnKukhS9gQSymPCvMXjvi2a34Oknzn1IYYT2Ad-RHcYF3Xra15IsPpn8cNrnMx8ggjU~linUcOHWMPjHSuV0bx6hdmdcHaWAW40kB9OWXKHbE44eNksg4AKcEwRhMcVn8-0JhtdJONJI8R4zV0~xxq2giQJy0ksqQHuMK8Sz397CyrA68HDRIK3hUt28MPpQPJu7qRreUZw6LRf3NQI1sBxIl8ULAz3BdUb3RHg__&Key-Pair-Id=APKAIXAG65U6UUX7JAQQ">

**Comment by Peppermint1020** [comment]
In our original design, 'view more' is not a button, but a prompt to swipe down. Do we need to modify it to a button?

**Comment by Peppermint1020** [comment]
Modify 'view more' as a button
