### ISSUE TITLE
[BUG] Opening the Token Inbox results in “Inbox request failed” error

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#24]
### Current Behavior

Opening the Token Inbox immediately results in an "Inbox request failed" error displayed.

### Expected Behavior

Opening the Token Inbox loads the token inbox successfully.

### Steps To Reproduce

1. Navigate to the token inbox in app.
2. Observe the immediate "Inbox Request Failed" error.

### Environment

```markdown
- iOS
- Android
```

### Related Issues

- https://github.com/Outblock/FRW-iOS/issues/179

### Notes
![2024051612230579124195](https://github.com/Outblock/FRW/assets/14852344/22748369-23c6-4322-b5b8-bb5e36be8d22)

**Comment by Peppermint1020** [comment]
Token inbox has been temporarily removed, and I have confirmed with Hao that no users are using it.
