### ISSUE TITLE
[BUG] WalletConnect sometimes not prompting authentication in app for mobile<->mobile connections

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#25]
### Current Behavior

Connecting to an FCL application on mobile, selecting to use Flow Wallet Mobile, then selecting to open Flow Wallet in the frw-link website opens the Flow Wallet app, but fails to trigger authentication.

### Expected Behavior

Authentication is correctly triggered in the app for all requests.

### Steps To Reproduce

1. Navigate to an FCL application (eg; increment) on mobile
2. Connect Wallet
3. Select Flow Wallet Mobile
4. Select to open Flow Wallet in the frw-link website.
5. Observe authentication _sometimes_ fail to be triggered.

### Environment

```markdown
- iOS
- Android
```

**Comment by h0plo** [comment]
wallet connect does not generate QR on mobile and Wallet Mobile fails at authentication.

**Comment by Peppermint1020** [comment]
Connect Increment and wait them fix this issue.

**Comment by lmcmz** [comment]
The universal link is updated, it should work now.
hence, we can close this ticket
