### ISSUE TITLE
[Feature] Warn user when their account is below the storage minimum

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#26]
## Feature

If a user's account is below the storage minimum, their subsequent transactions will fail.

We must detect when the user is below their storage minimum and display a warning on the dashboard page, instructing them to get FLOW (and display the amount of FLOW to get) in order for their account to make new transactions.

**Comment by Peppermint1020** [comment]
@KK-UIUX

**Comment by JeffreyDoyle** [comment]
Closing in favour of: https://github.com/Outblock/FRW/issues/61
