### ISSUE TITLE
[Feature] Migrate lilico support FAQ to wallet.flow.com

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#27]
Flow Wallet Extension links to the old lilico support FAQ in this button:

<img width="1722" alt="Screen Shot 2024-06-03 at 10 06 54 AM" src="https://github.com/Outblock/FRW/assets/14852344/5db2c056-a97a-4a9a-a00f-017ef7941d39">

This must be moved to wallet.flow.com/contact

**Comment by Peppermint1020** [comment]
We already updated the 'Need Help' link to wallet.flow.com/contact in extension version 2.1.8.
