### ISSUE TITLE
[BUG] Unable to unlink account

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#28]
### Current Behavior

On Flow Wallet Extension, if a user has a linked account, and they select to unlink the account, the transaction fails and the application sometimes crashes.

### Expected Behavior

If the transaction succeeds, the application should refresh state, remove the linked account from the app, and set the active account in the wallet to the parent account of the previously linked account.

### Steps To Reproduce

1. Link an account to an account managed in Flow Wallet
2. Select to Unlink the Account.
3. Observe the app either crash / transaction fail.
4. Observe the now unlinked account is still active in the application.

### Environment

```markdown
- iOS
- Android
```

**Comment by Peppermint1020** [comment]
This bug already fixed in extension dev version 2.1.8
