### ISSUE TITLE
[BUG] Incorrect linked account heirarchy

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#29]
### Current Behavior

On Flow Wallet Extension, if a user has a linked account, in that account's settings, the application says that the account is linked to itself.

### Expected Behavior

- Account linking hierarchy is displayed consistently and correctly across all platforms (iOS, Android, Extension)

### Steps To Reproduce

1. Link an account to an account managed in Flow Wallet Extension.
2. Set the linked account as active in the wallet.
3. Observe in the linked account's settings, the account is incorrectly displayed as linked to itself.

### Environment

```markdown
- iOS
- Android
- Extension
```

**Comment by Peppermint1020** [comment]
- [x] extension
- [x] Android
- [x] ios
Hide linked account button in linked account's setting page.
