### ISSUE TITLE
[BUG] Connected devices sometimes fail to display in device list

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#3]
### Current Behavior

Third device _sometimes_ fails to display in device list.

### Expected Behavior

All connected devices display consistently in device list

### Steps To Reproduce

- Create account on Device 1 (eg: iPhone)
- Device backup on Device 2 (eg: iPad)
- Device backup to Device 3 (eg: iPad)
- Observe on Device 3, only Device 3 and Device 2 are shown in device list.
- Observe on Device 1, all of Device 1, 2 and 3 are shown in device list.

### Environment

```markdown
- iOS
```

**Comment by lmcmz** [comment]
Need further investigating

**Comment by JeffreyDoyle** [comment]
Closing in favour of #81
