### ISSUE TITLE
[BUG] Linked Account name & icon incorrectly displayed

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#34]
### Current Behavior

When an account is linked to Flow Wallet mobile, it's name and icon are not displayed in the account selector view.

### Expected Behavior

- When an account is linked to Flow Wallet mobile, it's name and icon are displayed in the account selector view.

## Steps to Reproduce

- Link a Dapper Wallet with some Fungible Token to Flow Wallet
- Observe the name of the linked account as one the default names (eg: Lion/Panda/Koala)
- Observe the icon of the linked account as one the default icons (eg: Lion/Panda/Koala)

## Expected Outcomes

- [x] The correct name and icon are displayed for Linked Accounts

## Platforms

- [x] iOS
- [x] Android

**Comment by Peppermint1020** [comment]
The issue already fixed in ios version 2.1.7(5) and Android version i1.2.4
