### ISSUE TITLE
[BUG] Account Keys not displaying on Flow Wallet Extension

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#36]
### Current Behavior

When viewing Account Keys on Flow Wallet Extension, the keys fail to display.

### Expected Behavior

- When viewing Account Keys on Flow Wallet Extension, keys display as expected.

## Steps to Reproduce

- Open Flow Wallet Extension
- Navigate to Settings > Wallet > [Account] > Account Keys

## Expected Outcomes

- [x] The correct Account Keys display as expected

## Platforms

- [x] Extension

## Details:
<img width="407" alt="Screen Shot 2024-07-02 at 1 16 11 PM" src="https://github.com/Outblock/FRW/assets/14852344/20f46091-12fb-4581-bef1-48a416a213fb">

**Comment by Peppermint1020** [comment]
This issue already fixed in extension prod version 2.4.9
