### ISSUE TITLE
[Feature] Improve Accounts List for > 3 accounts

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#4]
### Feature

In the account list on Flow Wallet, when a user has >3 accounts, it's not obvious to the user that the list scrolls to view more accounts. The list should be more obvious that it's scrollable, expand larger to fit more of the screen, and be searchable.

![side bar](https://github.com/Outblock/FRW/assets/14852344/4009ddc6-a746-45f2-b126-09830f81472f)

**Comment by lmcmz** [comment]
@KK-UIUX  Need more account chip alert

**Comment by lmcmz** [comment]
# iOS
- [x] Scroll bar indicator
- [x] More chips
- [x] Swipe up to expand

# Android
- [x] Scroll bar indicator
- [x] More chips
- [x] Swipe up to expand#16 

# Extension
- [x] More chips
