### ISSUE TITLE
Support EIP-6963 on Flow Wallet Extension

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#40]
## Feature

Flow Wallet Extension needs to support EIP-6963 (https://eips.ethereum.org/EIPS/eip-6963#provider-info) when connecting to EVM apps in order to be supported by various wallet aggregator platforms like RainbowKit.

## Expected Outcomes

- [x] Flow Wallet Extension supports EIP-6963

## Platforms

- [x] Extension

**Comment by Peppermint1020** [comment]
Tested  by connecting with https://bridge.flow.com/
