### ISSUE TITLE
[BUG] Cannot create EVM account on Flow Wallet Extension

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#41]
### Current Behavior

When creating an EVM COA account, the transaction fails to submit

### Expected Behavior

- When creating an EVM COA account, the transaction completes successfully and the account is created

## Steps to Reproduce

- Open Flow Wallet Extension
- Navigate to Sidebar
- Select 'Enable path to EVM on Flow'
- Observe the button fail to trigger the transaction

## Expected Outcomes

- [x] EVM accounts are created successfully

## Platforms

- [x] Extension

## Details:
<img width="393" alt="Screen Shot 2024-09-09 at 5 46 02 PM" src="https://github.com/user-attachments/assets/5f82d252-3b4b-4eeb-8dd6-a303068bf1ba">
<img width="407" alt="Screen Shot 2024-09-06 at 9 00 40 AM" src="https://github.com/user-attachments/assets/921d057a-4bfd-4c81-9dca-60e6fd7fab25">

**Comment by Peppermint1020** [comment]
This issue already fixed in Extension version 2.4.9
