### ISSUE TITLE
[BUG] FT balances not displaying correctly on application load

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#42]
### Current Behavior

When viewing FT balance on the app at load, the balance isn't displayed correctly.

### Expected Behavior

- When opening the app on Android, the users FT balances (eg: FLOW) display as 0, once the app is refreshed then the correct balance is displayed.

## Steps to Reproduce

- Open Flow Wallet Android
- Observe 0 balance for FLOW displayed
- Refresh the app
- Observe correct balance of FLOW displayed

## Expected Outcomes

- [ ] Correct balance of FT are displayed on load

## Platforms

- [ ] Android

**Comment by Peppermint1020** [comment]
https://github.com/Outblock/FRW-Android/issues/292
