### ISSUE TITLE
[BUG] 'Move' functionality should be hidden when the user doesn't have an account to move assets to

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#43]
### Current Behavior

When a user doesn't have a linked account / EVM COA, the 'Move' functionality in the app is broken as there is not a destination account to move assets to.

### Expected Behavior

- Move functionality is hidden when there isn't another account in the user's profile to move assets to.

## Steps to Reproduce

- Open Flow Wallet Extension using a profile without a COA or LinkedAccount
- Select "Move" on the wallet dashboard
- Observe the functionality in a broken state

## Expected Outcomes

- [x] Move functionality is hidden when there isn't a destination to move assets to. 

## Platforms

- [x] Extension
- [x] iOS
- [x] Android

## Details:
<img width="388" alt="Screen Shot 2024-09-10 at 11 28 03 PM" src="https://github.com/user-attachments/assets/1fc3a283-3a92-48c4-8c36-09afaa289852">

**Comment by Peppermint1020** [comment]
Android

Need hide "move' button in token and NFT detail page when the user doesn't have an account to move asset to.
![Image](https://github.com/user-attachments/assets/6861601d-347a-422a-89a5-ba9ae3377821)
![Image](https://github.com/user-attachments/assets/be0b74d2-3152-427a-bdd0-60ffe979561c)


IOS:
Need add send button for nft when the user doesn't have an account to move asset to.
![Image](https://github.com/user-attachments/assets/2e1094f6-ecef-4132-a8d6-c397bd5aee2e)

**Comment by Peppermint1020** [comment]
Ios is cause by firebase config, will test when it lauch
