### ISSUE TITLE
[BUG] Authenticating with EVM applications prompts incorrect network switch to previewnet

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#44]
### Current Behavior

Authenticating with EVM applications prompts an incorrect network switch to previewnet

### Expected Behavior

- When authenticating with an EVM application, the wallet authenticates to that application using the correct network.

## Steps to Reproduce

- Open Flow Wallet Extension
- Navigate to an EVM application
- Authenticate with the application
- Observe the wallet try to switch to previewnet

## Expected Outcomes

- [x] Authentication happens successfully on the correct network

## Platforms

- [x] Extension
- [x] iOS
- [x] Android

**Comment by Peppermint1020** [comment]
This issue already fixed in extension 2.4.9, ios 2.1.11(5), Androidr2.4.11
