### ISSUE TITLE
[BUG] EVM Token Balances incorrectly/inconsitantly displaying 

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#46]
### Current Behavior

When viewing token balances of a COA account within Flow Wallet extension, sometimes FT balances (eg: FLOW) display incorrectly.

### Expected Behavior

- All FT balances are displayed correctly and consistently in the application.

## Steps to Reproduce

- Open Flow Wallet Extension
- Create a COA if one does not already exist
- Deposit some FLOW to the COA.
- Observe the balance inconsistently displayed. 

## Expected Outcomes

- [x] All FT balances are displayed correctly and consistently in the application.

## Platforms

- [x] Extension

**Comment by Peppermint1020** [comment]
This issue already fixed in Extension 2.4.9.
<img width="460" alt="Screen Shot 2024-09-18 at 10 39 39 am" src="https://github.com/user-attachments/assets/c41b73fb-8575-4537-975e-917e6ec4dde6">
