### ISSUE TITLE
[Feature] Remove account 'quick switch'

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#5]
# Feature

The account 'quick switch' feature must be removed until we enable user-defined profile pictures or otherwise make it more obvious which profile icon corresponds to which account. Until that time, we must remove the quick switch feature.

![side bar (3)](https://github.com/Outblock/FRW/assets/14852344/31f95d0c-cc5a-431a-ad5b-c1b3dca0f621)

**Comment by Peppermint1020** [comment]
Extension version 2.1.7(debug) already moved this feature.


![Image](https://github.com/Outblock/FRW/assets/87978227/cdd4c6e2-6597-4591-928f-1b32aadc41d9)

**Comment by Peppermint1020** [comment]
Android prod version i1.1.4 already moved this feature.


![Image](https://github.com/Outblock/FRW/assets/87978227/07349d1f-dbde-4c80-95cc-2b5cab9f6f05)

**Comment by Peppermint1020** [comment]
Ios dev version 1.0.0(38) already removed this feature.


![Image](https://github.com/Outblock/FRW/assets/87978227/c00173c1-e102-4252-b507-6978e5795b29)
