### ISSUE TITLE
[BUG] Flow Rewards Collection Setup + Metadata issues

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#50]
### Current Behavior

Users who own existing Flow Rewards NFTs are being asked to enable the Flow Rewards NFT Collection even though they already have one enabled on their account.

The Flow Rewards collection metadata also fails to display.

### Expected Behavior

- Users with an existing Flow Rewards NFT collection aren't prompted to set up a new one (same for all other NFT collections)
- MetaData for the Flow Rewards NFT collection displays correctly in wallet.

## Steps to Reproduce

- Aquire a Flow Rewards NFT using rewards.flow.com
- Observe incorrect metadata displayed for the Flow Rewards NFT collection
- Observe the wallet allow you to enable the Flow Rewards NFT collection even though it's already enabled on the account

## Expected Outcomes

- [ ] All Flow Rewards NFT collection metadata is displayed correctly
- [ ] Users with an existing collection aren't prompted to create a new one.

## Platforms

- [ ] Extension

## Details:
![Screenshot 2024-09-16 at 4 50 03 PM](https://github.com/user-attachments/assets/93558b07-165e-47ac-b9c3-2aee69b646c3)
![Screenshot 2024-09-16 at 4 50 03 PM](https://github.com/user-attachments/assets/d592b3b3-6273-4bbc-99ee-983215502223)
![Screenshot 2024-09-16 at 4 58 21 PM](https://github.com/user-attachments/assets/c20244a4-9571-47f4-a8f7-e990e4436707)
![Screenshot 2024-09-16 at 4 58 30 PM](https://github.com/user-attachments/assets/efa2c716-c69f-4e3f-a12e-070f081a1920)

**Comment by Peppermint1020** [comment]
This issue already fixed in mobile and extension.
