### ISSUE TITLE
[BUG] FT Price Issues

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#53]
### Current Behavior

Some chrome extension users are reporting issues with the price feed for certain assets, including aiSports and USDC.e.

### Expected Behavior

The correct price is displayed at all times for all FT assets

## Steps to Reproduce

- Aquire an account with some USDC.e or aiSports.
- Observe the incorrect price information (0$) displayed.

## Expected Outcomes

- [x] Flow Wallet extension displays the correct price information for all FT assets.

## Platforms

- [x] Extension

## Details:

![image (17)](https://github.com/user-attachments/assets/fb45c005-0263-4c40-8d5b-32c9415d3c01)

**Comment by Peppermint1020** [comment]
This bug is fixed.
Price of USDC.e displayed correctly now.
For ai.sport as the name of the token is change to JUICE, so the price is not shown correct in our app. We already correct it in our token list.
