### ISSUE TITLE
[BUG] Issue connecting to certain application via Wallet Connect on Flow Wallet Mobile

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#54]
### Current Behavior

Flow Wallet mobile is unable to authenticate via wallet connect to certain applications, including https://www.ankr.com/staking/stake/flow/ .

When authenticating, the error "Approve failed" is displayed after the user selects "connect" on the authentication prompt.

### Expected Behavior

- The user can authenticate successfully with all applications on Flow using Flow Wallet mobile.

## Steps to Reproduce

- Create an account with Flow Wallet mobile.
- Navigate to https://www.ankr.com/staking/stake/flow/ and login using wallet connect
- Observe the error "approve failed" displayed in the mobile app.

## Expected Outcomes

- [ ] All wallet profiles across iCloud and device backups are able to be restored.

## Platforms

- [ ] iOS (Tested on version 2.2.6)
- [ ] Android

**Comment by lmcmz** [comment]
For walletconnect, there are `requiredNamespace` and `optionalNamespace`. 
And ankr's request using eth mainnet as required Namespace, which flow wallet can't satisfy.

The issue should be fixed on ankr side

![image](https://github.com/user-attachments/assets/ac3f0c77-8ca8-4641-b185-a13624d7f36f)

**Comment by Peppermint1020** [comment]
Test on IOS version 2.2.9(8)
Failed to connect with flow wallet. Stuck in wallet connect pop up.
https://github.com/user-attachments/assets/e7697cba-b410-46d7-80ca-9e0c31163228

**Comment by lmcmz** [comment]
It has been fixed on ankr end
