### ISSUE TITLE
[BUG] Flow Wallet not displaying wFLOW token

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#56]
### Current Behavior

Flow Wallet is currently unable to display wFLOW FT balances

### Expected Behavior

- Flow Wallet can successfully transfer all known FTs including wFLOW.

## Steps to Reproduce

- Aquire wFLOW on EVM on Flow
- Observe Flow Wallet fail to display the wFLOW balance

## Expected Outcomes

- [x] Flow Wallet can successfully transfer all known FTs including wFLOW.

## Platforms

- [x] Extension
- [x] iOS
- [x] Android

**Comment by Peppermint1020** [comment]
https://spot.trado.one/trade/swap
contract address:0x5c147e74d63b1d31aa3fd78eb229b65161983b2b

**Comment by Peppermint1020** [comment]
Flow Wallet can successfully transfer all known FTs including wFLOW.
