### ISSUE TITLE
[BUG] Flow Wallet incompatibility issues with Trado

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#57]
### Current Behavior

Flow Wallet is currently incompatible with several user journeys on Trado.com (deployed to EVM on Flow), that are currently compatible with EOA wallets such as MetaMask etc. 

Such user journeys include:

- Trado SWAP (Swap cannot be used because Approve never happens - wFLOW to USDC.e)
- Trado POOL (Add liquidity functionality cannot be used because Approve never happens - wFLOW to USDC.e)
- Trado FARM (Add liquidity functionality just breaks with an error)

### Expected Behavior

- Flow Wallet can successfully sign any EVM transaction on EVM on Flow that is otherwise compatible with EOA wallet providers such as MetaMask etc.

## Steps to Reproduce

- Trado SWAP (Swap cannot be used because Approve never happens - wFLOW to USDC.e)
  - https://www.loom.com/share/1dd5a9d30d90407a86b78c9fc323846a?sid=261ef24e-caae-450a-a715-f3bef82aa87c 
- Trado POOL (Add liquidity functionality cannot be used because Approve never happens - wFLOW to USDC.e)
  - https://www.loom.com/share/1dd5a9d30d90407a86b78c9fc323846a?sid=261ef24e-caae-450a-a715-f3bef82aa87c
- Trado FARM (Add liquidity functionality just breaks with an error)
  - https://www.loom.com/share/cb51ed50f0ae4c788b43b864950c311c?sid=97bca50c-503d-4377-acdd-c1f69271eee6 

## Expected Outcomes

- [x] Flow Wallet can successfully sign any EVM transaction on EVM on Flow that is otherwise compatible with EOA wallet providers such as MetaMask etc.
- [x] The highlighted user journeys are compatible with Flow Wallet

## Platforms

- [x] Extension
- [x] iOS
- [x] Android

**Comment by Peppermint1020** [comment]
Can not find "Add liquidity" button in farm page.
![Image](https://github.com/user-attachments/assets/76ac126c-dd5d-4c2a-8632-9b8bd898c21d)

**Comment by franklywatson** [comment]
<img width="1271" alt="Screenshot 2024-10-28 at 10 11 43 AM" src="https://github.com/user-attachments/assets/5e57c9cf-51c9-4e69-89a5-eb359eca4f4e">
You have to open one of the rows

**Comment by Peppermint1020** [comment]
Extension prod version 2.5.16
(1) Succeed in TRADO SWAP
(2)Succeed in add liquidity for TRADO POOL. 
https://evm.flowscan.io/tx/0x02368de584732e3432c95a5a83ea2b036d749cdfc9c0cceb3b0e12b60701219a

(3)Succeed in add liquidity for TRADO Farm.
https://evm.flowscan.io/tx/0x11f5a042c269ae233dd686d954fc17774dc3b93766be7ce3504eac974ece2e7f

**Comment by Peppermint1020** [comment]
@zhouxl 
IOS prod version 2.2.9(7)
(1) Succeed in TRADO SWAP
(2)Succeed in TRADO POOL
(3) Failed in TRADO FARM
Error tx id: https://evm.flowscan.io/tx/0xa8a0c81e844b61220d58f372c7402582e9e22b01a13bf36f94502376af35b5fc

Update: 3) Succeed in TRADO FARM in iOS prod version 2.2.9(9)

**Comment by Peppermint1020** [comment]
Android prod version i1.5.22
(1) Succeed in TRADO SWAP
(2)Succeed in TRADO POOL
(3) Succeed in TRADO FARM: https://evm.flowscan.io/tx/0xae2d1d51e9322cd46009cd22ef65976378f251d133f4bf5b2ae2b092a3cc6ae6
