### ISSUE TITLE
[BUG] Errors displaying st.FLOW balance

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#59]
### Current Behavior

Users are reporting issues with accounts that have st.FLOW not having their balances display correctly, nor the price of st.FLOW displaying correctly. 

### Expected Behavior

The correct price and balance is displayed for accounts containing st.FLOW

## Steps to Reproduce

- Aquire an account with some st.FLOW
- Observe an incorrect balance and price displayed

## Expected Outcomes

- [ ] Flow Wallet displays the correct balance and price for st.FLOW

## Platforms

- [x] Extension
- [x] iOS
- [x] Android

**Comment by Peppermint1020** [comment]
**Tested on Extension prod version 2.5.16**
(1) Price of st.FLOW in EVM account is 0.
![Image](https://github.com/user-attachments/assets/e9a523b9-49b4-4371-878b-0dc6b8d9967e)

@zzggo 

**Update: Tested on Extension prod version 2.5.17**
The correct price and balance is displayed for st.FLOW in EVM account.
![Image](https://github.com/user-attachments/assets/760772fd-5312-4346-8811-fac8b48b7e19)

**Comment by Peppermint1020** [comment]
**Tested on iOS prod version 2.2.9(8)**
(1) Price of st.FLOW in FLOW account is 1.
(2)Price of st.FLOW in EVM account is 1.
![Image](https://github.com/user-attachments/assets/b81d8d58-265d-40cd-b4db-3a9f636cea79)
@zhouxl 

Update Tested on iOS prod version 2.2.9((10)
(1) Correct price of st.FLOW in FLOW account.
![Image](https://github.com/user-attachments/assets/4d836d49-bba6-4c68-881d-4483d6097508)

(2)Correct price of st.FLOW in EVM account.
![Image](https://github.com/user-attachments/assets/27ef3d3c-f3cd-4bc0-b788-f0d9c42497ad)
