### ISSUE TITLE
[BUG] Cannot transfer full balance of FT

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#6]
### Current Behavior

When transferring USDC (or other FT), Flow Wallet prevents sending the full balance of tokens, with the error "wallet balance can't fall below 0.001 flow" (which is the account storage minimum for FLOW token, but doesn't apply for other FTs)

### Expected Behavior

The full balance of any FT, other than FLOW, can be transferred.

### Steps To Reproduce

1. Aquire some USDC
2. Transfer full USDC balance to another account
3. Observe the error "wallet balance cant fall below 0.0001 FLOW"

### Environment

```markdown
- iOS
- Extension
```

**Comment by lmcmz** [comment]
@caosbad We need a script to calculate user minimum flow storage amount, then we can find the maximum sendable amount.

**Comment by lmcmz** [comment]
## iOS
- [x] Flow new minimum amount 
- [x] Other FT send full amount
- [x] Ignore COA Flow account 

## Android
- [x] Flow new minimum amount
- [x] Other FT send full amount
- [x] Ignore COA Flow account 

## Extension
- [x] Flow new minimum amount
- [x] Other FT send full amount
- [x] Ignore COA Flow account
