### ISSUE TITLE
[Feature] Loading state on original device when adding a new device backup

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#7]
# Feature

When adding a device backup, on the original device, there should be:

- (If possible) A loading indicator to display on the original device while the new device is being linked.
- Faster loading time on the original device once the device link is complete.

Currently, once a user device links to a new device, it's confusing to the user why the new device doesn't immediately appear on the original devices device list .

**Comment by lmcmz** [comment]
<img width="373" alt="Screenshot 2024-05-06 at 1 53 30 PM" src="https://github.com/Outblock/FRW/assets/9669733/cab52619-545d-422f-870b-bdd412d476b1">

**Comment by lmcmz** [comment]
- [x] iOS
- [x] Android

**Comment by Peppermint1020** [comment]
This UI design already add in Android prod version i1.1.5

**Comment by Peppermint1020** [comment]
This UI design already add in iOS prod version i.1.3(4)
