### ISSUE TITLE
[Feautre] Remove "Since" and number of NFTs in profile card

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#9]
# Feature

The profile card incorrectly displays the "Since" field. We should remove the since and number of NFT fields entirely. 

![side bar (1)](https://github.com/Outblock/FRW/assets/14852344/912a7f80-03f7-40fe-bf8f-bcf9a7b8190d)

**Comment by Peppermint1020** [comment]
These features already been moved in ios dev version 1.0.0(38) and Android prod version i1.1.4.
